[package]
name = "goose_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
local-ip-address = "=0.6.1"
serde = { version = "1.0.201", features = ["derive"] }
toml = "0.8.12"

